const FAKEUSERS = [
    {
        id: 1,
        title: "Title one",
        username: "LiaSanford",
        avatar: "https://i.picsum.photos/id/469/200/200.jpg?hmac=r_nEPJ5ExnhVEQSrNc19WUPConxJzBC929FJHl_Y5N4",
        content: "https://loremflickr.com/640/360",
        likes: 0,
        isOnline: true,
    },
    {
        id: 2,
        title: "Title two",
        username: "JamalArias",
        avatar: "https://i.picsum.photos/id/469/200/200.jpg?hmac=r_nEPJ5ExnhVEQSrNc19WUPConxJzBC929FJHl_Y5N4",
        content: "https://loremflickr.com/640/360",
        likes: 0,
    },
    {
        id: 3,
        title: "Title three",
        username: "MaeReynolds",
        avatar: "https://i.picsum.photos/id/469/200/200.jpg?hmac=r_nEPJ5ExnhVEQSrNc19WUPConxJzBC929FJHl_Y5N4",
        content: "https://loremflickr.com/640/360",
        likes: 0,
    },
    {
        id: 4,
        title: "Title four",
        username: "AngusVargas",
        avatar: "https://i.picsum.photos/id/469/200/200.jpg?hmac=r_nEPJ5ExnhVEQSrNc19WUPConxJzBC929FJHl_Y5N4",
        content: "https://loremflickr.com/640/360",
        likes: 0,
    },
    {
        id: 5,
        title: "Title five",
        username: "Saul Woodward",
        avatar: "https://i.picsum.photos/id/469/200/200.jpg?hmac=r_nEPJ5ExnhVEQSrNc19WUPConxJzBC929FJHl_Y5N4",
        content: "https://loremflickr.com/640/360",
        likes: 0,
    },
    {
        id: 6,
        title: "Title six",
        username: "CaitlynCurtis",
        avatar: "https://i.picsum.photos/id/469/200/200.jpg?hmac=r_nEPJ5ExnhVEQSrNc19WUPConxJzBC929FJHl_Y5N4",
        content: "https://loremflickr.com/640/360",
        likes: 0,
    },
    {
        id: 7,
        title: "Title seven",
        username: "VioletMcleod",
        avatar: "https://i.picsum.photos/id/469/200/200.jpg?hmac=r_nEPJ5ExnhVEQSrNc19WUPConxJzBC929FJHl_Y5N4",
        content: "https://loremflickr.com/640/360",
        likes: 0,
    },
    {
        id: 8,
        title: "Title eight",
        username: "ErikDale",
        avatar: "https://i.picsum.photos/id/469/200/200.jpg?hmac=r_nEPJ5ExnhVEQSrNc19WUPConxJzBC929FJHl_Y5N4",
        content: "https://loremflickr.com/640/360",
        likes: 0,
    },
]


export default FAKEUSERS;